/* GitHub Pages: crawlable lesson documents without relying on hash routing. */
import {readFileSync,writeFileSync,mkdirSync} from 'node:fs';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url)),base='https://emredursun.github.io/quilyn/';
const registry=JSON.parse(readFileSync(resolve(root,'data/registry.json')));
const esc=v=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const urls=[''];
function emit(path,text){if(process.argv.includes('--check')){if(readFileSync(resolve(root,path),'utf8')!==text)throw new Error('Static page is stale: '+path);}else{mkdirSync(resolve(root,path.substring(0,path.lastIndexOf('/'))),{recursive:true});writeFileSync(resolve(root,path),text);}}
function page(path,title,description,content,depth){const up='../'.repeat(depth);return '<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+esc(title)+' — Quilyn</title><meta name="description" content="'+esc(description)+'"><link rel="canonical" href="'+base+path+'"><meta property="og:title" content="'+esc(title)+' — Quilyn"><meta property="og:description" content="'+esc(description)+'"><meta property="og:url" content="'+base+path+'"><meta property="og:type" content="article"><link rel="icon" href="'+up+'icon.svg"><link rel="stylesheet" href="'+up+'core/css/reading-page.css"></head><body><a class="skip" href="#content">Skip to content</a><header><a class="brand" href="'+up+'index.html#home"><img src="'+up+'icon.svg" width="36" height="36" alt="">Quilyn</a><nav aria-label="Primary"><a href="'+up+'learn/">All tracks</a><a href="'+up+'index.html#library">Learning library</a></nav></header><main id="content">'+content+'</main><footer>Independent study notes. Quilyn is not affiliated with or endorsed by the certification providers. Practice content is not an official exam bank.</footer></body></html>\n';}
function element(e){switch(e.type){case 'concept':return '<article><h3>'+esc(e.term)+'</h3><p>'+esc(e.description)+'</p>'+(e.items?'<ul>'+e.items.map(i=>'<li>'+esc(i)+'</li>').join('')+'</ul>':'')+'</article>';case 'text':case 'note':case 'warning':case 'analogy':return '<p>'+esc(e.text)+'</p>';case 'bullets':return '<ul>'+(e.items||[]).map(i=>'<li>'+esc(i)+'</li>').join('')+'</ul>';case 'table':return '<div class="table-scroll"><table>'+(e.headers?'<thead><tr>'+e.headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead>':'')+'<tbody>'+(e.rows||[]).map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';case 'links':return '<ul>'+(e.items||[]).filter(i=>/^https:\/\//.test(i.url)).map(i=>'<li><a href="'+esc(i.url)+'" rel="noopener noreferrer">'+esc(i.label)+'</a></li>').join('')+'</ul>';default:return '';}}
for(const track of registry.tracks){const slug=track.trackId.toLowerCase(),path='learn/'+slug+'/',ready=track.modules.filter(m=>m.ready!==false);urls.push(path);
 const rows=[];
 for(const meta of ready){const d=JSON.parse(readFileSync(resolve(root,meta.file))),moduleSlug=meta.id.toLowerCase(),lessonPath=path+moduleSlug+'/',title=d.moduleTitle||meta.name;urls.push(lessonPath);
  rows.push('<li><a href="'+moduleSlug+'/">'+esc(title)+'</a></li>');
  const description='Study '+title+' for '+track.trackName+'. Independent learning notes with source links and interactive practice in Quilyn.';
  const contents='<nav aria-label="Breadcrumb"><a href="../">'+esc(track.trackName)+'</a> / '+esc(title)+'</nav><h1>'+esc(title)+'</h1><p>'+esc(description)+'</p><p class="meta">'+esc(d.platformVersion?'Version '+d.platformVersion:'Version not documented')+' · '+esc(d.sourceReviewedOn?'Source reviewed '+d.sourceReviewedOn:'Source review date not documented')+'</p><p><a class="button" href="../../../index.html#'+track.trackId+'/'+meta.id+'">Open interactive lesson and quiz</a></p><nav aria-label="Lesson topics"><ul>'+d.studyGuide.map(s=>'<li><a href="#'+s.sectionId+'">'+esc(s.sectionTitle)+'</a></li>').join('')+'</ul></nav>'+d.studyGuide.map(s=>'<section id="'+s.sectionId+'"><h2>'+esc(s.sectionTitle)+'</h2>'+s.elements.map(element).join('')+'</section>').join('')+'<p>Exercises, diagrams and practice feedback are available in the interactive lesson.</p><p><a href="'+esc(d.moduleUrl)+'" rel="noopener noreferrer">Provider learning source</a></p>';
  emit(lessonPath+'index.html',page(lessonPath,title+' | '+track.trackId,description,contents,3));
 }
 emit(path+'index.html',page(path,track.trackName+' study guide','Explore '+ready.length+' independent study modules for '+track.trackName+' with source references and quizzes.','<h1>'+esc(track.trackName)+'</h1><p>Independent study notes and practice. '+ready.length+' modules available.</p><p><a class="button" href="../../index.html#'+track.trackId+'">Start interactive learning</a></p><ul>'+rows.join('')+'</ul>',2));
}
urls.push('learn/');emit('learn/index.html',page('learn/','Certification learning tracks','Browse independent study guides for Pega, Tricentis Tosca and Testim certification learning tracks.','<h1>Certification learning tracks</h1><p>Choose a track to browse lessons. Use the interactive app to save progress and practice.</p><ul>'+registry.tracks.map(t=>'<li><a href="'+t.trackId.toLowerCase()+'/">'+esc(t.trackName)+'</a></li>').join('')+'</ul>',1));
const sitemap='<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+urls.map(p=>'  <url><loc>'+base+p+'</loc></url>').join('\n')+'\n</urlset>\n';
if(process.argv.includes('--check')){if(readFileSync(resolve(root,'sitemap.xml'),'utf8')!==sitemap)throw new Error('Sitemap is stale');}else writeFileSync(resolve(root,'sitemap.xml'),sitemap);
console.log('Static reading pages verified: '+(urls.length-1)+', with canonical URLs and sitemap.');
